-- 1. Create the table
create table if not exists public.registered_student (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  whatsapp text not null,
  level text not null
);

-- 2. Enable Row Level Security (Security best practice)
alter table public.registered_student enable row level security;

-- 3. Create a policy to allow anyone (anonymous users) to INSERT data
-- This is required because RLS is enabled by default on new tables in some Supabase setups
create policy "Enable insert for everyone"
on public.registered_student
for insert
to anon
with check (true);

-- 4. Grant usage on the sequence (sometimes needed for ID generation)
grant usage on sequence registered_student_id_seq to anon;
grant all on table registered_student to anon;
grant all on table registered_student to service_role;
