-- 1. Create the 'courses' table
create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  course_name text not null,
  instructor text not null,
  duration_days integer,
  online_classes text,
  category text,
  is_active boolean default true,
  remark text
);

-- 2. Insert initial data from JSON
insert into public.courses (course_name, instructor, duration_days, online_classes, category, is_active, remark)
values 
('Introduction to AI & Machine Learning', 'Sehan Arandara', 60, '16 days / 8 weeks - 2 classes per week', 'AI ML', true, 'Perfect for beginners starting their AI journey'),
('Full Stack Web Development', 'Sehan Arandara', 90, '24 days / 12 weeks - 2 classes per week', 'Web Dev', true, 'Covers React, Node.js, and Supabase');

-- 3. Create the 'registered_student' table (Drop existing one if you are in development to enforce FK)
-- NOTE: In production, use ALTER TABLE instead.
drop table if exists public.registered_student;

create table if not exists public.registered_student (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  whatsapp text not null,
  level text not null,
  course_id bigint references public.courses(id)
);

-- 4. Enable Row Level Security
alter table public.courses enable row level security;
alter table public.registered_student enable row level security;

-- 5. Policies
-- Simpler policy for development: Allow everything for everyone on courses
-- DROP existing policies first if you run this in SQL Editor manually
drop policy if exists "Allow public read access to active courses" on public.courses;
drop policy if exists "Allow admins to manage courses" on public.courses;

create policy "Allow full access to courses"
on public.courses for all
to anon
using (true)
with check (true);

-- Allow anyone to register (insert)
create policy "Enable insert for everyone"
on public.registered_student for insert
to anon
with check (true);

-- Grant permissions
grant usage on sequence courses_id_seq to anon;
grant select, insert, update, delete on table courses to anon;

grant usage on sequence registered_student_id_seq to anon;
grant all on table registered_student to anon;
grant all on table registered_student to service_role;

-- 6. Create the 'admin_users' table
create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  username text not null unique,
  password text not null,
  role text default 'admin'
);

-- Insert initial admin user
insert into public.admin_users (username, password, role)
values ('SehanAdmin', 'sehan+savi', 'admin')
on conflict (username) do nothing;

-- Enable RLS
alter table public.admin_users enable row level security;

-- Policy to allow anyone to read admin users (for the simple login check in frontend)
-- WARN: In a real app, never expose passwords this way. Use Supabase Auth.
-- But for this specific request context of manually checking a table:
create policy "Allow public read of admin users"
on public.admin_users for select
to anon
using (true);

-- Grant permissions
grant usage on sequence admin_users_id_seq to anon;
grant select on table admin_users to anon;
