-- 1. Create the 'courses' table
create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  course_name text not null,
  instructor text not null,
  duration_days integer,
  online_classes text,
  category text,
  is_active boolean default true,
  remark text
);

-- 2. Insert initial data from JSON
insert into public.courses (course_name, instructor, duration_days, online_classes, category, is_active, remark)
values 
('Introduction to AI & Machine Learning', 'Sehan Arandara', 60, '16 days / 8 weeks - 2 classes per week', 'AI ML', true, 'Perfect for beginners starting their AI journey'),
('Full Stack Web Development', 'Sehan Arandara', 90, '24 days / 12 weeks - 2 classes per week', 'Web Dev', true, 'Covers React, Node.js, and Supabase');

-- 3. Create the 'registered_student' table (Drop existing one if you are in development to enforce FK)
-- NOTE: In production, use ALTER TABLE instead.
drop table if exists public.registered_student;

create table if not exists public.registered_student (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  whatsapp text not null,
  level text not null,
  course_id bigint references public.courses(id)
);

-- 4. Enable Row Level Security
alter table public.courses enable row level security;
alter table public.registered_student enable row level security;

-- 5. Policies
-- Simpler policy for development: Allow everything for everyone on courses
-- DROP existing policies first if you run this in SQL Editor manually
drop policy if exists "Allow public read access to active courses" on public.courses;
drop policy if exists "Allow admins to manage courses" on public.courses;

create policy "Allow full access to courses"
on public.courses for all
to anon
using (true)
with check (true);

-- Allow anyone to register (insert)
create policy "Enable insert for everyone"
on public.registered_student for insert
to anon
with check (true);

-- Grant permissions
grant usage on sequence courses_id_seq to anon;
grant select, insert, update, delete on table courses to anon;

grant usage on sequence registered_student_id_seq to anon;
grant all on table registered_student to anon;
grant all on table registered_student to service_role;

-- 6. Create the 'admin_users' table
create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  username text not null unique,
  password text not null,
  role text default 'admin'
);

-- Insert initial admin user
insert into public.admin_users (username, password, role)
values ('SehanAdmin', 'sehan+savi', 'admin')
on conflict (username) do nothing;

-- Enable RLS
alter table public.admin_users enable row level security;

-- Policy to allow anyone to read admin users (for the simple login check in frontend)
-- WARN: In a real app, never expose passwords this way. Use Supabase Auth.
-- But for this specific request context of manually checking a table:
create policy "Allow public read of admin users"
on public.admin_users for select
to anon
using (true);

-- Grant permissions
grant usage on sequence admin_users_id_seq to anon;
grant select on table admin_users to anon;

-- 7. Update registered_student table to include payment and account status
alter table public.registered_student 
add column if not exists payment_status text default 'Pending',
add column if not exists account_status text default 'Inactive',
add column if not exists payment_verified_at timestamp with time zone,
add column if not exists verified_by text;

-- 8. Create LMS users table (for login credentials)
create table if not exists public.lms_users (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  student_id bigint references public.registered_student(id) on delete cascade,
  email text not null unique,
  password text not null,
  is_active boolean default true,
  last_login timestamp with time zone
);

-- 9. Create enrollment table
create table if not exists public.enrollments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  student_id bigint references public.registered_student(id) on delete cascade,
  lms_user_id bigint references public.lms_users(id) on delete cascade,
  course_id bigint references public.courses(id) on delete cascade,
  enrolled_by text,
  status text default 'active',
  completed_at timestamp with time zone,
  unique(student_id, course_id)
);

-- Enable RLS
alter table public.lms_users enable row level security;
alter table public.enrollments enable row level security;

-- Policies for lms_users
create policy "Allow public read of lms users"
on public.lms_users for select
to anon
using (true);

create policy "Allow insert of lms users"
on public.lms_users for insert
to anon
with check (true);

create policy "Allow update of lms users"
on public.lms_users for update
to anon
using (true);

-- Policies for enrollments
create policy "Allow full access to enrollments"
on public.enrollments for all
to anon
using (true)
with check (true);

-- Grant permissions
grant usage on sequence lms_users_id_seq to anon;
grant all on table lms_users to anon;

grant usage on sequence enrollments_id_seq to anon;
grant all on table enrollments to anon;

-- Update registered_student permissions to allow updates
grant update on table registered_student to anon;
