
-- 10. Create the 'course_roadmap' table
create table if not exists public.course_roadmap (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  course_id bigint references public.courses(id) on delete cascade,
  day_number integer not null,
  step_type text not null check (step_type in ('class', 'quiz', 'reading', 'assignment')),
  title text not null,
  description text,
  recording_url text,
  resource_url text,
  content jsonb, -- For quiz questions or reading content
  order_index integer default 0,
  is_published boolean default true
);

-- 11. Create student progress tracking
create table if not exists public.student_progress (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  student_id bigint references public.lms_users(id) on delete cascade,
  course_id bigint references public.courses(id) on delete cascade,
  step_id bigint references public.course_roadmap(id) on delete cascade,
  status text default 'completed' check (status in ('locked', 'unlocked', 'completed')),
  completed_at timestamp with time zone default timezone('utc'::text, now()),
  unique(student_id, step_id)
);

-- 12. Create student_streaks table (Optional but good for Snapchat-style tracking)
create table if not exists public.student_streaks (
  id bigint generated by default as identity primary key,
  student_id bigint references public.lms_users(id) on delete cascade,
  course_id bigint references public.courses(id) on delete cascade,
  current_streak integer default 0,
  longest_streak integer default 0,
  last_activity_date date default current_date,
  unique(student_id, course_id)
);

-- Enable RLS
alter table public.course_roadmap enable row level security;
alter table public.student_progress enable row level security;
alter table public.student_streaks enable row level security;

-- Policies
create policy "Allow all on roadmap" on public.course_roadmap for all to anon using (true) with check (true);
create policy "Allow all on progress" on public.student_progress for all to anon using (true) with check (true);
create policy "Allow all on streaks" on public.student_streaks for all to anon using (true) with check (true);

-- Grant permissions
grant usage on sequence course_roadmap_id_seq to anon;
grant all on table course_roadmap to anon;

grant usage on sequence student_progress_id_seq to anon;
grant all on table student_progress to anon;

grant usage on sequence student_streaks_id_seq to anon;
grant all on table student_streaks to anon;
